from rake_nltk import Rake

# Uses stopwords for english from NLTK, and all puntuation characters by
# default
r = Rake(max_length=2)

# mytext = '''
# Black-on-black ware is a 20th- and 21st-century pottery tradition developed by the Puebloan Native American ceramic artists in Northern New Mexico. Traditional reduction-fired blackware has been made for centuries by pueblo artists. Black-on-black ware of the past century is produced with a smooth surface, with the designs applied through selective burnishing or the application of refractory slip. Another style involves carving or incising designs and selectively polishing the raised areas. For generations several families from Kha'po Owingeh and P'ohwhóge Owingeh pueblos have been making black-on-black ware with the techniques passed down from matriarch potters. Artists from other pueblos have also produced black-on-black ware. Several contemporary artists have created works honoring the pottery of their ancestors.
# '''

mytext = """
The use of information and communications technologies (ICTs) to address a wide array of development issues has gained considerable attention among governments, practitioners, and researchers in recent years. While early studies focused on mobile phones and text messaging, that attention is quickly shifting to other media, including video. Studies on the video medium tend to explore the pathway leading from increase access and consumption of information to changes in behaviors that result in welfare-improving outcomes. Chong and Ferrara and Jensen and Oster demonstrate that exposure to TV soap operas featuring strong women and smaller families led to reduced fertility and increased women’s autonomy. Berg and Zia and Banerjee et al. rely on videos purposefully designed to convey specific messages on issues such as financial literacy or HIV prevention. Bernard et al.  shows that screening short documentaries featuring rural individuals who improved their life outcomes through perseverance and hard work led to significant changes in viewers’ perceptions and futureoriented behavior. Similarly, Riley shows that screening an inspirational movie to secondary school students containing a locally relevant theme and a strong role model significantly improved educational attainment.
The video medium offers several advantages over many other ICT-based information dissemination approaches. First, videos can be tailored and customized to address localized information needs and context. Several studies demonstrate the importance of locally relevant information, drawing attention to evidence from studies in the economics on education, entrepreneurship and agriculture. Psychologists similarly find a positive relationship between locally relevant information and public health, weight gains, smoking habits , and education. Second, videos can encourage role model effects. Role models who are similar to individuals across multiple dimensions of character or identity can encourage them to receive, accept, and internalize messages that lead to desirable changes in behavior. Video-based content can provide exposure to role models, substituting for the individual’s experience or the experience of actual peers while framing messages to promote attitude and behavior change. Third, videos can allow for consistent content delivery, thereby reducing errors in conveying sensitive and detailed technical information and countering the adverse effects of unmotivated agents. This can be particularly important when learning about complex behaviors or practices. Fourth, videos can be produced at a relatively low fixed cost, which increases the approach’s cost effectiveness as the number of viewers increases. Whether used alone or in tandem with other approaches to information dissemination, video can be a powerful medium.
Our study explores these issues in the context of smallholder agriculture in lower-income countries with a basic question: does video-mediated agricultural extension lead to increased and sustained uptake of agricultural technologies and practices by smallholder farmers?1 We explore these questions in the context of a large-scale rollout of a video-mediated extension approach by the Government of Ethiopia and Digital Green over a two-year period. Our study further asks whether video-mediated extension targeted at both spouses of a household is more effective than when only targeted at the (typically male) household head. We also provide insights into the mechanisms driving the observed effects, and an analysis of the cost-effectiveness of the video-mediated approach with respect to promoting the adoption of pre-determined agricultural practices. Although our study is primarily designed to assess the effect on adoption, we also investigate the resulting effects of adoption on farmers’ yields. Importantly, our study is integrated into the government’s efforts to assess existing extension systems program reforms; and is thus a directly policy-relevant evaluation. To the best of our knowledge, few studies have sought to measure the effectiveness of videos in promoting agricultural technologies with any degree of rigor or at any sizeable scale (see periodic reviews by Spielman et al., Fabregas et al., Nakasone and Torero, and Aker). Vasilaky et al. assessed the effectiveness of a video-mediated approach to promoting the system of rice intensification (SRI) among smallholder farmers in Bihar, India, and found that the approach increased the probability of adoption by 5 percentage points among those who viewed videos, which translated to a 50 percent increase over the mean of their control group. Hörner et al. assessed the effect of decentralized agricultural extension services and a video intervention on the adoption of integrated soil fertility management in Ethiopia; but found no marginal gains in adoption resulting from the video intervention. Van Campenhout et al. experimented with video-based agricultural extension in Uganda and found significant effects on maize farmers’ knowledge, input use, and technology adoption. Dzanku et al. found significant effects for an intervention combining video documentaries and radio listening clubs on the uptake of rhizobium inoculation and legume yields in Ghana but were unable to disentangle the effect of the two interventions.
Our study extends this work with new evidence on the effectiveness of the video medium not only to convey information to farmers, but also to advance gender-relevant augmentations to public extension service provision. In doing so, we shift the focus of inquiry from small experiments to a large-scale evaluation of a public program designed to promote the adoption of agricultural technologies and practices. We also shift attention from the role of ICTs in accelerating the adoption of discrete technologies—new varieties or inorganic fertilizers—to more complex management practices, and from conventional input-targeting models to more complex multi-object learning models. Further, our study explores both learning externalities and dis-adoption dynamics by virtue of its multi-year duration, similar to Oyinbo et al., who also studied the sustained impact of site-specific nutrient management recommendations provided through digital support tools in Nigeria. Our study also introduces a gender dimension to shed light on knowledge accumulation and decisionmaking within smallholder agricultural households.
Finally, our study expands the emerging literature on the role of ICTs in developing-country agriculture. To date, most studies in this literature have focused on evaluating simple, low-cost text and voice messaging services provided to farmers over mobile networks, and more often for price-related information. Fewer studies examine the role of ICTs in the provision of productionrelated information and advice. Exceptions include the use of short message services containing information on crop management advice and weather forecasts in India; integrated pest management practices in Ecuador; agronomic advice in India and Kenya; radio and mobile phone services to promote certified seeds and fertilizer in Senegal; animated videos on post-harvest management in Burkina Faso; insecticidal neem use in Benin; interactive crop advisory services via mobile phones in India; targeted/site-specific nutrient management recommendations through digital support tools in Nigeria and Ethiopia; and the video-based interventions noted earlier. Results from these studies vary from no effects of the ICT-based approach on technology adoption, production, or yields to significant changes in input and technology use and yields/profits, suggesting the importance of replication to appropriately reflect the context specificity of each intervention. Our results demonstrate that the video-mediated extension approach led to increases in the uptake of key agricultural technologies and practices that were recommended by public extension providers, rural administrators, and researchers. In the first year of the experiment, we find a 6 percentage points overall increase in farmers’ uptake of the recommended technologies, which translates into a 10 percent increase over the mean of the control group. Across technologies, we find that the videomediated approach resulted in a 13, 20 and 15 percent increase in uptake over control group means for row planting, precise seeding rate, and urea top/side dressing, respectively. These results endure in the second year of the experiment, pointing to farmers’ effective uptake of the technologies beyond a mere trial in one production season. From these effects, we compute the marginal cost-effectiveness of the video-mediated approach under experimental and scale-up (‘‘full saturation”) scenarios. The cost of each additional adoption under the experimental scenario ranges from USD 16 – 30. However, these figures decrease to USD 3 – 6 when we assume that the video-mediated approach is extended to all kebeles (village clusters) in the treatment woredas (districts).
Exploring the mechanisms that explain these adoption effects, we find that the video-mediated extension approach led to an increase in extension reach, with a 35 percent increase in farmers’ attendance to extension sessions likely due to increased interest by farmers in the medium. In turn, we find a higher level of knowledge—greater technical understanding of the subject technologies and practices—among farmers in kebeles randomly assigned to the video-mediated extension approach. While our results also point to greater participation and knowledge gains among (typically female) spouses who also participated in the videomediated extension approach, we do not find clear evidence that targeting both spouses translated into higher technology uptake rates. Lastly, we do not find clear evidence that the increased adoption of the technologies promoted by the Ethiopian public extension system translated into higher yields. These null yield results may be related to issues of measurement error, insufficient adaptation of the technologies to context, or other factors discussed later.
The remainder of this paper is organized as follows. Section 2 provides background to the evaluation. Section 3 presents the experimental design of the study including the interventions and treatment arms, timing, sampling, and experimental integrity. Section 4 discusses the empirical strategy, followed by results of the intervention’s primary impacts in Section 5. Section 6 provides an analysis of the intervention’s cost-effectiveness, while Section 7 concludes with policy implications of the findings, avenues for future research, and concluding thoughts.
"""

# Extraction given the text.
r.extract_keywords_from_text(mytext)

# Extraction given the list of strings where each string is a sentence.
#r.extract_keywords_from_sentences(<list of sentences>)

# To get keyword phrases ranked highest to lowest.
print(r.get_ranked_phrases())

# To get keyword phrases ranked highest to lowest with scores.
print(r.get_ranked_phrases_with_scores())